export const GET_GENRES_REQUEST = 'GET_GENRES_REQUEST';
export const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
export const GET_GENRES_FAILURE= 'GET_GENRES_FAILURE';

export const GET_GENRE_REQUEST = 'GET_GENRE_REQUEST';
export const GET_GENRE_SUCCESS = 'GET_GENRE_SUCCESS';
export const GET_GENRE_FAILURE= 'GET_GENRE_FAILURE';

export const GET_ALBUMS_REQUEST = 'GET_ALBUMS_REQUEST';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_FAILURE= 'GET_ALBUMS_FAILURE';

export const GET_ALBUM_REQUEST = 'GET_ALBUM_REQUEST';
export const GET_ALBUM_SUCCESS = 'GET_ALBUM_SUCCESS';
export const GET_ALBUM_FAILURE= 'GET_ALBUM_FAILURE';

export const GET_ARTISTS_REQUEST = 'GET_ARTISTS_REQUEST';
export const GET_ARTISTS_SUCCESS = 'GET_ARTISTS_SUCCESS';
export const GET_ARTISTS_FAILURE= 'GET_ARTISTS_FAILURE';

export const GET_ARTIST_REQUEST = 'GET_ARTIST_REQUEST';
export const GET_ARTIST_SUCCESS = 'GET_ARTIST_SUCCESS';
export const GET_ARTIST_FAILURE= 'GET_ARTIST_FAILURE';

export const GET_SONGS_REQUEST = 'GET_SONGS_REQUEST';
export const GET_SONGS_SUCCESS = 'GET_SONGS_SUCCESS';
export const GET_SONGS_FAILURE= 'GET_SONGS_FAILURE';

export const GET_SONG_REQUEST = 'GET_SONG_REQUEST';
export const GET_SONG_SUCCESS = 'GET_SONG_SUCCESS';
export const GET_SONG_FAILURE= 'GET_SONG_FAILURE';